name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x, oldstable, stable]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Test
        run: go test -v ./...
