name: validate
on: [push, pull_request]

permissions:
  contents: read

jobs:
  linters:
    strategy:
      matrix:
        go-version: [1.19.x, oldstable, stable]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          # TODO use --out-format=junit-xml and store artifacts
          args: --print-resources-usage --timeout=10m --verbose
